### ISSUE TITLE
Support Paragon Reputation

### ISSUE THREAD

**Issue by NoShotz** [DJScias/Experiencer2#2]
Would be nice if the experience/rep bar would support paragon rep. Currently the bar just stays in a semi bugged state when you have it showing reputations you have maxed out that have paragon rep.

![image](https://github.com/DJScias/Experiencer2/assets/13302841/23f15890-6bdb-4977-80b2-92b2c883d624)

![image](https://github.com/DJScias/Experiencer2/assets/13302841/b13e62ae-c803-45df-8349-7d749a676b0a)

Sidenote, real nice seeing this addon updated, used to use it before it stopped getting updated.

**Comment by DJScias** [comment]
Hello there!

Thank you for this report.

I did a few checks and notice Paragon does seem to work for most reputations on my end, so I think it's only bugged for the new ones that work with renown as of Dragonflight.

![image](https://github.com/DJScias/Experiencer2/assets/439655/f451dacd-198e-43de-9ce7-a23d44826ad7)

Could you check if the non-renown ones work as they should though with Paragon for you as well? That way I can get a second confirmation on my guess here.

I probably missed this initially as I frankly don't have a single renown high enough to get into paragon levels yet.. But it's good to know they can do it so I can take a deeper look.

Thanks in advance.

**Comment by NoShotz** [comment]
For other reputations it does seem to work, however it just says exalted instead of paragon like in your screenshot.

![image](https://github.com/DJScias/Experiencer2/assets/13302841/ece5d353-2830-4646-84fc-c9da1c521d54)

**Comment by DJScias** [comment]
Hello there,

I see, thank you. It seems when I check on Argussian Reach it also just uses "Exalted".
![image](https://github.com/DJScias/Experiencer2/assets/439655/69a120ae-0e1f-4a68-9ee4-465acd1fef3a)

However I've noticed a few issues in how it defines when displaying Paragon vs Exalted which I'll take a look at soon.
I'll see if that might also fix the Renown Paragon, but I can't make any promises as the fix for that part would be theoretical because I don't have any Paragon options yet for my Dragonflight renowns.

Thank you for providing me all the information though, this'll help me a lot in getting this sorted.

**Comment by DJScias** [comment]
This should be resolved in 5.2.0.
